// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:pizza_hub/assets/secrets.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: web_api,
    appId: '1:458734553619:web:46551710a9a759e4f60de6',
    messagingSenderId: msg_senderID,
    projectId: 'pizzahub-7c3a5',
    authDomain: 'pizzahub-7c3a5.firebaseapp.com',
    storageBucket: 'pizzahub-7c3a5.appspot.com',
    measurementId: 'G-27ZYFSYCFS',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: android_api,
    appId: '1:458734553619:android:6bea6274a36b8adcf60de6',
    messagingSenderId: msg_senderID,
    projectId: 'pizzahub-7c3a5',
    storageBucket: 'pizzahub-7c3a5.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: ios_api,
    appId: '1:458734553619:ios:e7820b29e9c27cb4f60de6',
    messagingSenderId: msg_senderID,
    projectId: 'pizzahub-7c3a5',
    storageBucket: 'pizzahub-7c3a5.appspot.com',
    iosBundleId: 'com.example.pizzaHub',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: macos_api,
    appId: '1:458734553619:ios:8d709242ccd89dc6f60de6',
    messagingSenderId: msg_senderID,
    projectId: 'pizzahub-7c3a5',
    storageBucket: 'pizzahub-7c3a5.appspot.com',
    iosBundleId: 'com.example.pizzaHub.RunnerTests',
  );
}
